services:
  - type: web
    name: flask-form-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --timeout 120 app:app"
    envVars:
      - key: PORT
        value: 8000