services:
  - type: web
    name: wetransfer-clone
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SENDER_EMAIL
        value: nwekee125@gmail.com
      - key: SENDER_PASSWORD
        value: wpse tggu zdza cvxq
      - key: RECEIVER_EMAIL
        value: maxwell202201@gmail.com
